// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCw-i75cFXJ9pyXX6QBBX4D0WAv4zrisc',
    appId: '1:779145413441:android:5a14350dd32a2648a197c0',
    messagingSenderId: '779145413441',
    projectId: 'ronvest-app-1',
    databaseURL: 'https://ronvest-app-1-default-rtdb.firebaseio.com',
    storageBucket: 'ronvest-app-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-HQ0EUEMvV_Ip9kPNQDvQJySsHpYWSPQ',
    appId: '1:779145413441:ios:50fad1713f0db290a197c0',
    messagingSenderId: '779145413441',
    projectId: 'ronvest-app-1',
    databaseURL: 'https://ronvest-app-1-default-rtdb.firebaseio.com',
    storageBucket: 'ronvest-app-1.appspot.com',
    iosClientId: '779145413441-hnsid8m6i2dpothu8v0e2sr94fsgpdhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.ronvestApp',
  );
}
